
//export const LOGIN_USER = 'LOGIN_USER';

//export const UPDATE_REGISTERED_USER = 'UPDATE_REGISTERED_USER';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTRATION_SUCCESSFUL = 'REGISTRATION_SUCCESSFUL';

export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS';

export const VERIFICATION_FAILED = 'VERIFICATION_FAILED';

export const GET_USERS = 'GET_USERS';

export const AUTO_LOGIN_ATTEMPT = 'AUTO_LOGIN_ATTEMPT';

export const AUTO_LOGIN_ATTEMPT_FAILED = 'AUTO_LOGIN_ATTEMPT_FAILED';